# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests and pnpm audit.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup pnpm and Node.js ${{ matrix.node-version }}
      uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
      with:
        runtime: node@24
        cache: true
    - run: git submodule update --init --recursive
    - if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
      run: pnpm audit
    - run: pnpm lint
    - run: pnpm test
    - run: pnpm data-files-ad-block-rust
    - run: pnpm data-files-local-data-files
    - run: pnpm data-files-leo-local-models
